# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: 'janvince.smallmessages::lang.plugin.controllers.categories.reorder.label'

# Attribute name
nameFrom: title

# Model Class name
modelClass: JanVince\SmallMessages\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar